// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHvzlA-KIeHNqsBaLQl68868H7_A9IigQ',
    appId: '1:721816280273:web:7330b8e0fd5043821379f0',
    messagingSenderId: '721816280273',
    projectId: 'virtuo-90db3',
    authDomain: 'virtuo-90db3.firebaseapp.com',
    storageBucket: 'virtuo-90db3.appspot.com',
    measurementId: 'G-NEWTKFFS3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5yWNtDWtxkeRY01uALxfpmkMfwowf60Y',
    appId: '1:721816280273:android:6f942232360a25c01379f0',
    messagingSenderId: '721816280273',
    projectId: 'virtuo-90db3',
    storageBucket: 'virtuo-90db3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMHkeO_h3TXyf6omj5-piIFpzbc9knTkU',
    appId: '1:721816280273:ios:650aab784579cb5c1379f0',
    messagingSenderId: '721816280273',
    projectId: 'virtuo-90db3',
    storageBucket: 'virtuo-90db3.appspot.com',
    iosClientId: '721816280273-csmjgvnjpiu18695mugndp45h8d22103.apps.googleusercontent.com',
    iosBundleId: 'com.example.virtuo',
  );
}
